### ISSUE TITLE
Rename "How you can help" to "Easy ways to contribute"?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#154]
This is for example used in https://wiki.typo3.org/Document_Matrix

I never was really happy with the title but did not come up with a better title at that time.

**Comment by susannemoog** [comment]
Tbh I think "How you can help" is fine here because the main menu entry this belongs to is "Contribute to the TYPO3 Documentation" and duplicating the "contribute" is unnecessary. Additionally, I shy away from using words like "easy" as we are judging the users skill level and capabilities by suggesting that if they find something on that list "hard", it's their fault.
I would close this issue for now, if someone comes up with a better naming, we can revisit the topic.

**Comment by sypets** [comment]
Agree. Thanks for taking care of it. 

>  I shy away from using words like "easy" as we are judging the users skill level and capabilities by suggesting that if they find something on that list "hard", it's their fault.

Agree. This is also in Symfony docs style guide: 

> Avoid belittling words: Things that seem "obvious" or "simple" for the person documenting it, can be the exact opposite for the reader. To make sure everybody feels comfortable when reading the documentation, try to avoid words like:
> basically
> clearly
> easy/easily

https://symfony.com/doc/current/contributing/documentation/standards.html#english-language-standards

and was already corrected and pointed out somewhere else by someone else (don't remember exactly where + who).
