### ISSUE TITLE
Add guidelines for image icon shadows

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#174]
Following the TYPO3 guidelines to create screenshots with icons for the TYPO3 docs at https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/GuidelinesForImages.html , at the bottom of this guide there are some arrows and rectangles with shadows applied: there should be declared official shadow parameters there.

**Comment by alexander-nitsche** [comment]
As suggested and approved by Philipp Randt, the official TYPO3 documentation icon shadow should have these params:

- Blur: 10px
- Offset: 4px 4px
- Type: outer shadow
- Color: rgba(0, 0, 0, 0.3)

and look like this:

![DistributionDatabaseExport3](https://user-images.githubusercontent.com/20297232/96856553-532ef600-145e-11eb-9f8f-a0781383cefe.png)

**Comment by sypets** [comment]
@alexander-nitsche The part [Guidelines for screenshots with graphics elements
](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/GuidelinesForImages.html#guidelines-for-screenshots-with-graphics-elements) generally needs more work. Especially the proposed icons (arrows, boxes, numbers etc.)

Some more background information: 

* My goal was to create a set of icons to be used for images, see https://github.com/TYPO3-Documentation/images 
* It is also possible to create **one** SVG from these (as "symbols") and make them importable. I tested this with Inkscape, see also https://softwarerecs.stackexchange.com/questions/74442/workflow-and-tools-to-augment-screenshots-with-custom-arrows-numbers-boxes-etc
* the design team supplied a set of icons, but this is currently not sufficient, because 
  * there are different oranges being used and this clashes with current docs.typo3.org colors
  * the icons should be easy to use and I think they currently aren't (e.g. creating boxes and aligning the numbers)
  
About the different oranges, see [Color scheme (orange) of docs.typo3.org inconsistent with TYPO3 style guide](https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/79)

What would be really helpful would be to first decide a color scheme for the icons (**I would not use orange because of the named problems**).

It's important to use colors so that icons stand out from the images (which may be dark or light, e.g. screenshots from TYPO3 backend).

Then decide about some icon shapes. I personally would prefer to use something like

* numbers in circles which you already see in existing docs
* the already often used arrow, but in different color, see https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/_images/BackendFileModule.png

But I like your examples, so maybe it is enough to just change the color from orange.


---

Since I already made several attempts to solve this and I am not a designer, I would strongly appreciate if someone would take over this task. It look like you are already doing this. 

Please also look at already existing images, e.g. https://www.google.com/search?q=site:docs.typo3.org&client=ubuntu&hs=8AI&sxsrf=ALeKk00zW2cQ_dFp-cKubQUyz95QuBJuZw:1603368331185&source=lnms&tbm=isch&sa=X&ved=2ahUKEwil4su-lMjsAhUkUBUIHblCDSMQ_AUoAXoECAsQAw&biw=1920&bih=1072#imgrc=5saizxD9j2nanM

**Comment by alexander-nitsche** [comment]
Hi Sybille, 
thanks for your feedback. I take it as good-to-know for future works in this screenshot+icons area, but this PR focuses only on shadows of icons. There has already a shadow been applied to some images with icons on https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/GuidelinesForImages.html but there was no hint of their parameters. The design team told me which parameters to use and i added these parameters to this page and replaced all shadows in the images by the new shadow style. I did not want to add new examples nor touch the whole topic of icons with this PR.
Greetings, Alex

**Comment by sypets** [comment]
ok. I think we can add your texts to the page and replace the images. If you want you can create a PR.

On a side not - I added some of the images and I am not happy with the result. Like I said, I am not a designer.

**Comment by alexander-nitsche** [comment]
Creating another PR than this one?

**Comment by sypets** [comment]
We are currently in an issue. But, I saw you now, you already create a PR: #175 

Sorry, ignore my previous comment.
