### ISSUE TITLE
Fix guideline of list indentations

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#176]
Currently the documentation guide mainly requires sub lists to be separated by a blank line and indented by 3 white spaces. This is true for the blank line but not always for the indentation: The sub list should always be aligned with the first letter of the text of the parent list item.

For example:

```
* Parent list item text

  * Sub list item indented by 2 ws

*. Parent list item text with a dot

   *. Sub list item indented by 3 ws
```

This issue is about reworking all lists and how-tos of lists in the guideline accordingly.

See https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#bullet-lists .

**Comment by marble** [comment]
I don't know what we are currently, writing in our guide, but I just want to throw in, that I, personally in my own documents, tend **to always use and indentation of three for lists.** 
This is because in .editorconfig we have that setting of three, and I can just type "*", TAB, Text of list item. This make rearrangement of multiline list items easier, as I can use TAB for this:

    1234567890

    *  The T at the beginning of this line is in column three, as there are "*", " ", " " precedding it
       The T at the beginning of this line is in column three.
       The T at the beginning of this line is in column three

.

**Comment by alexander-nitsche** [comment]
Ok, makes sense. The above example would change then to
```
*  Parent list item text

   *  Sub list item indented by 3 ws

*. Parent list item text with a dot

   *. Sub list item indented by 3 ws
```
This would still require a rework of the lists but a different explanation in the how-tos of lists.

**Comment by marble** [comment]
I fixed my example.
