### ISSUE TITLE
Define rules for link targets

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#180]
Related: TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1125

We should define rules for link targets:

* upper / lowercase
* dashes or not

## About upper / lowercase

Link targets with upper-lowercase are converted into all lowercase. You can see this in the linktargets page and in what is appended to the URL.

Example

```
.. _SomeFunction:

SomeFunction
===========
```

Both work: 

```
:ref:`SomeFunction`
:ref:`somefunction`
```

But it shows up as somefunction in link targets page and is appended to URL as such: `#somefunction`

**Comment by marble** [comment]
This turned out to be **best practice** for me. **In general,** example:

    .. _Report-an-Issue:

    Report an Issue
    ============

with these rules to create the reference target:

1. Duplicate the headline
2. Replace all blanks by a hyphen
3. Remove all non-alphanumeric characters or replace them by a hyphen
4. Add `.. _` at the beginning.
5. Add `:` at the end.
6. The allowed character set for reference targets is alphanumeric plus hyphen and underscore (`[a-z][A-Z][0-9][-_]`).

Sphinx keeps and retains the upper and lower case spelling of the targets but ignores it when resolving the symbol to find the link address. In other words: Crossreferencing WORKS independently of case, that is, cas insensitive. But in a list of available reference targets the spelling is still shown as spedified. This is an adavantage and increases readability.

With long headlines it may be wise to use a shorter slug. In other situations it may be wise to use prefixes for certain targets. Think of a set of configuration values. Then targets like `configvalue-width`, `configvalue-verbose` and so on may be appropriate.

**Comment by linawolf** [comment]
Link anchors: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/Reference/ReStructuredText/Content/Links.html#explicit-link-targets are sluggified by the new rendering and the popoup window makes it easier to link to them.
