### ISSUE TITLE
Integrate Slack discussion: How to link between changelog RST files

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#182]
https://typo3.slack.com/archives/C028JEPJL/p1607463666006400

**Comment by susannemoog** [comment]
@marble I just read that discussion and tried to see what / how we should document that here - as Sybille pointed out, it is already documented, as an exception for the changelog case, which makes sense, as linking with `:ref:` is superior if possible as it is stable across renames and moves of content and files. I would therefore close this issue here. If you feel like there should be additional content added to the docs, please reopen the issue and describe the necessary content.
