### ISSUE TITLE
Idea to expand "How you can help" for people who want to make fast contributions

### ISSUE THREAD

**Issue by nearlythere** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#20]
Problem: As a casual contributor, I want a guide on "how to get started quickly." The TYPO3 community said contribution is easy and fast, so show me the main things I need to know fast. 

To solve this, I propose making the "How you can help" page more like a quick start. https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/HowYouCanHelp.html

Here are the other similar top-level pages, but seem to be more comprehensive and details. 
- How To Document TYPO3 Projects https://docs.typo3.org/typo3cms/HowToDocument/Index.html
 - Contains short summary of what that "How to document" manual is
- Contributing to official documentation is a longer introduction https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/Index.html
- Docs » About TYPO3 Documentation » Contribute. Doesn't have as much detail. https://docs.typo3.org/Contribute/Index.html

What do you think about this outline for “How you can help”? It might repeat somethings elsewhere, but could be a good landing page for “I want to do something quick, how can I start?”

- Before your first contribution
    - What they need. GitHub Account, etc. Link to guidelines.
- Explain “Fast online contributions”
    - Small fixes, typos, corrections, etc.
    - Emphasize the workflow is easy, every gets reviewed.
    - Link to the [GitHub Method](https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/GithubMethod.html )
- What kinds of quick contributions can you make?
    - Similar to what is on here already https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/HowYouCanHelp.html
    - E.g., Start with a favourite manual you’re familiar with.
    - Update content/images/ etc.
- Explain what wouldn’t be a quick contribution
    - Refactoring, new sections, etc. 
    - Link to comprehensive docs on the contribution workflow, emphasize if they have ideas to start with an issue. 
    - Should link to more info about the contribution workflow. Maybe link to this? https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/Quickstart.html

Sort of based on https://symfony.com/doc/current/contributing/documentation/overview.html

**Comment by sypets** [comment]
@nearlythere I like the Symfony documentation you linked to very much. Not sure if the "How you can help" page is the right place though, because that is a list of things for how you can help - big and small, not everything is suited for getting started. 

I think your goal is a **"getting started" page** with everything on it to get started, step by step and not too much text and fluff, so I'll try to focus on that using the Symfony page as role model.

Another note on "Edit me on Github": While it's supposed to be easy and is easy for making small changes, for developers it may actually be easier and more familiar to use the "git / docker method", because that is what they are used to when contributing to other open source projects (local editing and using git to commit and push from their local system). For developers (or rather for people familiar with making Github Pull Request using local tools, including git and familiar with docker), it might even be better to point them to the "git / docker method". You can actually test the rendering properly and use your preferred editor or IDE. The Symfony page does a good job of using both methods, but it does not really clarify the difference very well, IMHO. So, I'm still ambivalent where we should direct people for a quick start. Being confronted with 2 different methods when you are just getting started ... not really ideal either. 

Experienced developers can be newbies in documenting too and even the geeks out there who miraculously understand the inner working of TYPO3 seem a bit put off by reST sometimes. Not easy to get it right for everybody.  

Anyway, I'll do some more thinking and hopefully can get this done this weekend.

See also #27

**Comment by sypets** [comment]
Please see updated page https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/Index.html.

I also added some things to [How you can help](https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/HowYouCanHelp.html).

**Comment by nearlythere** [comment]
That is perfect! Love that page. Clear and actionable. Thanks so much for sorting this out in such a short time. I think we’ll be doing another post in January too (typo3.org) - so that will be another chance, with more warning heh.
